#include <stdlib.h>
#include "ioctl.h"
#include "tsbapi/tsb_admin.h"
#include "tsbapi/tsb_tnc_session.h"
enum {
	COMMAND_TNC_GET_NOTIFY = 0x50,
	COMMAND_TNC_CREATE_SESSION,
	COMMAND_TNC_DELETE_SESSION,
	COMMAND_TNC_SET_POLICY,
	COMMAND_TNC_GET_SESSION
};

#define IOCTL_TNC_SET_POLICY	HTTC_IO_COMMAND(COMMAND_TNC_SET_POLICY)
#define IOCTL_TNC_GET_NOTIFY	HTTC_IO_COMMAND(COMMAND_TNC_GET_NOTIFY)
#define IOCTL_TNC_CREATE_SESSION	HTTC_IO_COMMAND(COMMAND_TNC_CREATE_SESSION)
#define IOCTL_TNC_GET_SESSION	HTTC_IO_COMMAND(COMMAND_TNC_GET_SESSION)
#define IOCTL_TNC_DELETE_SESSION	HTTC_IO_COMMAND(COMMAND_TNC_DELETE_SESSION)



