#ifndef __TCS_NOTICE_DEF_H__
#define __TCS_NOTICE_DEF_H__

enum{
	NOTICE_BLOCK_EXIT,					//终止通知阻塞
	NOTICE_TRUSTED_STATUS_CHANGED,		//可信状态改变
	NOTICE_LICENSE_STATUS_CHANGED,		//License授权状态改变
	NOTICE_POLICIES_VERSION_UPDATED,	//策略版本更新
	NOTICE_TNC_AGREEMENTA_FAILED,		//可信协商失败
	NOTICE_TNC_CREATE_SESSION,			//创建会话通知
	NOTICE_TNC_DELETE_SESSION,			//(主动)删除会话通知
	NOTICE_TNC_SESSION_EXPIRE_ALL,		//会话过期通知(被动删除)
	NOTICE_TNC_SESSION_EXPIRE_HALF,		//会话单向过期通知(双向变单向)
	NOTICE_POLICIES_SOURCE_UPDATED,		//策略来源更新
};

#endif

