// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: migrate.proto

#include "migrate.pb.h"
#include "migrate.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace virtrust {
namespace protos {

static const char* MigrationService_method_names[] = {
  "/virtrust.protos.MigrationService/PrepareMigration",
  "/virtrust.protos.MigrationService/ExchangePkAndReport",
  "/virtrust.protos.MigrationService/StartMigration",
  "/virtrust.protos.MigrationService/SendVRsourceData",
  "/virtrust.protos.MigrationService/NotifyVRMigrateResult",
  "/virtrust.protos.MigrationService/DomainMigrate",
};

std::unique_ptr< MigrationService::Stub> MigrationService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MigrationService::Stub> stub(new MigrationService::Stub(channel, options));
  return stub;
}

MigrationService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_PrepareMigration_(MigrationService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ExchangePkAndReport_(MigrationService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StartMigration_(MigrationService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendVRsourceData_(MigrationService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NotifyVRMigrateResult_(MigrationService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DomainMigrate_(MigrationService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MigrationService::Stub::PrepareMigration(::grpc::ClientContext* context, const ::virtrust::protos::PrepareMigRequest& request, ::virtrust::protos::PrepareMigReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::virtrust::protos::PrepareMigRequest, ::virtrust::protos::PrepareMigReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PrepareMigration_, context, request, response);
}

void MigrationService::Stub::async::PrepareMigration(::grpc::ClientContext* context, const ::virtrust::protos::PrepareMigRequest* request, ::virtrust::protos::PrepareMigReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::virtrust::protos::PrepareMigRequest, ::virtrust::protos::PrepareMigReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PrepareMigration_, context, request, response, std::move(f));
}

void MigrationService::Stub::async::PrepareMigration(::grpc::ClientContext* context, const ::virtrust::protos::PrepareMigRequest* request, ::virtrust::protos::PrepareMigReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PrepareMigration_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::virtrust::protos::PrepareMigReply>* MigrationService::Stub::PrepareAsyncPrepareMigrationRaw(::grpc::ClientContext* context, const ::virtrust::protos::PrepareMigRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::virtrust::protos::PrepareMigReply, ::virtrust::protos::PrepareMigRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PrepareMigration_, context, request);
}

::grpc::ClientAsyncResponseReader< ::virtrust::protos::PrepareMigReply>* MigrationService::Stub::AsyncPrepareMigrationRaw(::grpc::ClientContext* context, const ::virtrust::protos::PrepareMigRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPrepareMigrationRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MigrationService::Stub::ExchangePkAndReport(::grpc::ClientContext* context, const ::virtrust::protos::EXchangePkAndReportRequest& request, ::virtrust::protos::EXchangePkAndReportReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::virtrust::protos::EXchangePkAndReportRequest, ::virtrust::protos::EXchangePkAndReportReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExchangePkAndReport_, context, request, response);
}

void MigrationService::Stub::async::ExchangePkAndReport(::grpc::ClientContext* context, const ::virtrust::protos::EXchangePkAndReportRequest* request, ::virtrust::protos::EXchangePkAndReportReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::virtrust::protos::EXchangePkAndReportRequest, ::virtrust::protos::EXchangePkAndReportReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExchangePkAndReport_, context, request, response, std::move(f));
}

void MigrationService::Stub::async::ExchangePkAndReport(::grpc::ClientContext* context, const ::virtrust::protos::EXchangePkAndReportRequest* request, ::virtrust::protos::EXchangePkAndReportReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExchangePkAndReport_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::virtrust::protos::EXchangePkAndReportReply>* MigrationService::Stub::PrepareAsyncExchangePkAndReportRaw(::grpc::ClientContext* context, const ::virtrust::protos::EXchangePkAndReportRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::virtrust::protos::EXchangePkAndReportReply, ::virtrust::protos::EXchangePkAndReportRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExchangePkAndReport_, context, request);
}

::grpc::ClientAsyncResponseReader< ::virtrust::protos::EXchangePkAndReportReply>* MigrationService::Stub::AsyncExchangePkAndReportRaw(::grpc::ClientContext* context, const ::virtrust::protos::EXchangePkAndReportRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExchangePkAndReportRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MigrationService::Stub::StartMigration(::grpc::ClientContext* context, const ::virtrust::protos::StartMigRequest& request, ::virtrust::protos::StartMigReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::virtrust::protos::StartMigRequest, ::virtrust::protos::StartMigReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StartMigration_, context, request, response);
}

void MigrationService::Stub::async::StartMigration(::grpc::ClientContext* context, const ::virtrust::protos::StartMigRequest* request, ::virtrust::protos::StartMigReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::virtrust::protos::StartMigRequest, ::virtrust::protos::StartMigReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartMigration_, context, request, response, std::move(f));
}

void MigrationService::Stub::async::StartMigration(::grpc::ClientContext* context, const ::virtrust::protos::StartMigRequest* request, ::virtrust::protos::StartMigReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartMigration_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::virtrust::protos::StartMigReply>* MigrationService::Stub::PrepareAsyncStartMigrationRaw(::grpc::ClientContext* context, const ::virtrust::protos::StartMigRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::virtrust::protos::StartMigReply, ::virtrust::protos::StartMigRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StartMigration_, context, request);
}

::grpc::ClientAsyncResponseReader< ::virtrust::protos::StartMigReply>* MigrationService::Stub::AsyncStartMigrationRaw(::grpc::ClientContext* context, const ::virtrust::protos::StartMigRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStartMigrationRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MigrationService::Stub::SendVRsourceData(::grpc::ClientContext* context, const ::virtrust::protos::VRsourceInfoRequest& request, ::virtrust::protos::VRsourceInfoReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::virtrust::protos::VRsourceInfoRequest, ::virtrust::protos::VRsourceInfoReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendVRsourceData_, context, request, response);
}

void MigrationService::Stub::async::SendVRsourceData(::grpc::ClientContext* context, const ::virtrust::protos::VRsourceInfoRequest* request, ::virtrust::protos::VRsourceInfoReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::virtrust::protos::VRsourceInfoRequest, ::virtrust::protos::VRsourceInfoReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendVRsourceData_, context, request, response, std::move(f));
}

void MigrationService::Stub::async::SendVRsourceData(::grpc::ClientContext* context, const ::virtrust::protos::VRsourceInfoRequest* request, ::virtrust::protos::VRsourceInfoReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendVRsourceData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::virtrust::protos::VRsourceInfoReply>* MigrationService::Stub::PrepareAsyncSendVRsourceDataRaw(::grpc::ClientContext* context, const ::virtrust::protos::VRsourceInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::virtrust::protos::VRsourceInfoReply, ::virtrust::protos::VRsourceInfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendVRsourceData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::virtrust::protos::VRsourceInfoReply>* MigrationService::Stub::AsyncSendVRsourceDataRaw(::grpc::ClientContext* context, const ::virtrust::protos::VRsourceInfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendVRsourceDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MigrationService::Stub::NotifyVRMigrateResult(::grpc::ClientContext* context, const ::virtrust::protos::MigrateResultRequest& request, ::virtrust::protos::MigrateResultReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::virtrust::protos::MigrateResultRequest, ::virtrust::protos::MigrateResultReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NotifyVRMigrateResult_, context, request, response);
}

void MigrationService::Stub::async::NotifyVRMigrateResult(::grpc::ClientContext* context, const ::virtrust::protos::MigrateResultRequest* request, ::virtrust::protos::MigrateResultReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::virtrust::protos::MigrateResultRequest, ::virtrust::protos::MigrateResultReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NotifyVRMigrateResult_, context, request, response, std::move(f));
}

void MigrationService::Stub::async::NotifyVRMigrateResult(::grpc::ClientContext* context, const ::virtrust::protos::MigrateResultRequest* request, ::virtrust::protos::MigrateResultReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NotifyVRMigrateResult_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::virtrust::protos::MigrateResultReply>* MigrationService::Stub::PrepareAsyncNotifyVRMigrateResultRaw(::grpc::ClientContext* context, const ::virtrust::protos::MigrateResultRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::virtrust::protos::MigrateResultReply, ::virtrust::protos::MigrateResultRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NotifyVRMigrateResult_, context, request);
}

::grpc::ClientAsyncResponseReader< ::virtrust::protos::MigrateResultReply>* MigrationService::Stub::AsyncNotifyVRMigrateResultRaw(::grpc::ClientContext* context, const ::virtrust::protos::MigrateResultRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNotifyVRMigrateResultRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MigrationService::Stub::DomainMigrate(::grpc::ClientContext* context, const ::virtrust::protos::DomainMigraterRequest& request, ::virtrust::protos::DomainMigraterReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::virtrust::protos::DomainMigraterRequest, ::virtrust::protos::DomainMigraterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DomainMigrate_, context, request, response);
}

void MigrationService::Stub::async::DomainMigrate(::grpc::ClientContext* context, const ::virtrust::protos::DomainMigraterRequest* request, ::virtrust::protos::DomainMigraterReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::virtrust::protos::DomainMigraterRequest, ::virtrust::protos::DomainMigraterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DomainMigrate_, context, request, response, std::move(f));
}

void MigrationService::Stub::async::DomainMigrate(::grpc::ClientContext* context, const ::virtrust::protos::DomainMigraterRequest* request, ::virtrust::protos::DomainMigraterReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DomainMigrate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::virtrust::protos::DomainMigraterReply>* MigrationService::Stub::PrepareAsyncDomainMigrateRaw(::grpc::ClientContext* context, const ::virtrust::protos::DomainMigraterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::virtrust::protos::DomainMigraterReply, ::virtrust::protos::DomainMigraterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DomainMigrate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::virtrust::protos::DomainMigraterReply>* MigrationService::Stub::AsyncDomainMigrateRaw(::grpc::ClientContext* context, const ::virtrust::protos::DomainMigraterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDomainMigrateRaw(context, request, cq);
  result->StartCall();
  return result;
}

MigrationService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MigrationService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MigrationService::Service, ::virtrust::protos::PrepareMigRequest, ::virtrust::protos::PrepareMigReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MigrationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::virtrust::protos::PrepareMigRequest* req,
             ::virtrust::protos::PrepareMigReply* resp) {
               return service->PrepareMigration(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MigrationService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MigrationService::Service, ::virtrust::protos::EXchangePkAndReportRequest, ::virtrust::protos::EXchangePkAndReportReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MigrationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::virtrust::protos::EXchangePkAndReportRequest* req,
             ::virtrust::protos::EXchangePkAndReportReply* resp) {
               return service->ExchangePkAndReport(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MigrationService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MigrationService::Service, ::virtrust::protos::StartMigRequest, ::virtrust::protos::StartMigReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MigrationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::virtrust::protos::StartMigRequest* req,
             ::virtrust::protos::StartMigReply* resp) {
               return service->StartMigration(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MigrationService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MigrationService::Service, ::virtrust::protos::VRsourceInfoRequest, ::virtrust::protos::VRsourceInfoReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MigrationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::virtrust::protos::VRsourceInfoRequest* req,
             ::virtrust::protos::VRsourceInfoReply* resp) {
               return service->SendVRsourceData(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MigrationService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MigrationService::Service, ::virtrust::protos::MigrateResultRequest, ::virtrust::protos::MigrateResultReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MigrationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::virtrust::protos::MigrateResultRequest* req,
             ::virtrust::protos::MigrateResultReply* resp) {
               return service->NotifyVRMigrateResult(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MigrationService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MigrationService::Service, ::virtrust::protos::DomainMigraterRequest, ::virtrust::protos::DomainMigraterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MigrationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::virtrust::protos::DomainMigraterRequest* req,
             ::virtrust::protos::DomainMigraterReply* resp) {
               return service->DomainMigrate(ctx, req, resp);
             }, this)));
}

MigrationService::Service::~Service() {
}

::grpc::Status MigrationService::Service::PrepareMigration(::grpc::ServerContext* context, const ::virtrust::protos::PrepareMigRequest* request, ::virtrust::protos::PrepareMigReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MigrationService::Service::ExchangePkAndReport(::grpc::ServerContext* context, const ::virtrust::protos::EXchangePkAndReportRequest* request, ::virtrust::protos::EXchangePkAndReportReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MigrationService::Service::StartMigration(::grpc::ServerContext* context, const ::virtrust::protos::StartMigRequest* request, ::virtrust::protos::StartMigReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MigrationService::Service::SendVRsourceData(::grpc::ServerContext* context, const ::virtrust::protos::VRsourceInfoRequest* request, ::virtrust::protos::VRsourceInfoReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MigrationService::Service::NotifyVRMigrateResult(::grpc::ServerContext* context, const ::virtrust::protos::MigrateResultRequest* request, ::virtrust::protos::MigrateResultReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MigrationService::Service::DomainMigrate(::grpc::ServerContext* context, const ::virtrust::protos::DomainMigraterRequest* request, ::virtrust::protos::DomainMigraterReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace virtrust
}  // namespace protos

