// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: migrate.proto
#ifndef GRPC_migrate_2eproto__INCLUDED
#define GRPC_migrate_2eproto__INCLUDED

#include "migrate.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace virtrust {
namespace protos {

// The greeting service definition.
class MigrationService final {
 public:
  static constexpr char const* service_full_name() {
    return "virtrust.protos.MigrationService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 1: 准备迁移
    virtual ::grpc::Status PrepareMigration(::grpc::ClientContext* context, const ::virtrust::protos::PrepareMigRequest& request, ::virtrust::protos::PrepareMigReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::PrepareMigReply>> AsyncPrepareMigration(::grpc::ClientContext* context, const ::virtrust::protos::PrepareMigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::PrepareMigReply>>(AsyncPrepareMigrationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::PrepareMigReply>> PrepareAsyncPrepareMigration(::grpc::ClientContext* context, const ::virtrust::protos::PrepareMigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::PrepareMigReply>>(PrepareAsyncPrepareMigrationRaw(context, request, cq));
    }
    // 2: 交换公钥
    virtual ::grpc::Status ExchangePkAndReport(::grpc::ClientContext* context, const ::virtrust::protos::EXchangePkAndReportRequest& request, ::virtrust::protos::EXchangePkAndReportReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::EXchangePkAndReportReply>> AsyncExchangePkAndReport(::grpc::ClientContext* context, const ::virtrust::protos::EXchangePkAndReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::EXchangePkAndReportReply>>(AsyncExchangePkAndReportRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::EXchangePkAndReportReply>> PrepareAsyncExchangePkAndReport(::grpc::ClientContext* context, const ::virtrust::protos::EXchangePkAndReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::EXchangePkAndReportReply>>(PrepareAsyncExchangePkAndReportRaw(context, request, cq));
    }
    // 3: 开始迁移
    virtual ::grpc::Status StartMigration(::grpc::ClientContext* context, const ::virtrust::protos::StartMigRequest& request, ::virtrust::protos::StartMigReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::StartMigReply>> AsyncStartMigration(::grpc::ClientContext* context, const ::virtrust::protos::StartMigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::StartMigReply>>(AsyncStartMigrationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::StartMigReply>> PrepareAsyncStartMigration(::grpc::ClientContext* context, const ::virtrust::protos::StartMigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::StartMigReply>>(PrepareAsyncStartMigrationRaw(context, request, cq));
    }
    // 4：迁移虚机密码资源
    virtual ::grpc::Status SendVRsourceData(::grpc::ClientContext* context, const ::virtrust::protos::VRsourceInfoRequest& request, ::virtrust::protos::VRsourceInfoReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::VRsourceInfoReply>> AsyncSendVRsourceData(::grpc::ClientContext* context, const ::virtrust::protos::VRsourceInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::VRsourceInfoReply>>(AsyncSendVRsourceDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::VRsourceInfoReply>> PrepareAsyncSendVRsourceData(::grpc::ClientContext* context, const ::virtrust::protos::VRsourceInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::VRsourceInfoReply>>(PrepareAsyncSendVRsourceDataRaw(context, request, cq));
    }
    // 5: 通知迁移结果
    virtual ::grpc::Status NotifyVRMigrateResult(::grpc::ClientContext* context, const ::virtrust::protos::MigrateResultRequest& request, ::virtrust::protos::MigrateResultReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::MigrateResultReply>> AsyncNotifyVRMigrateResult(::grpc::ClientContext* context, const ::virtrust::protos::MigrateResultRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::MigrateResultReply>>(AsyncNotifyVRMigrateResultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::MigrateResultReply>> PrepareAsyncNotifyVRMigrateResult(::grpc::ClientContext* context, const ::virtrust::protos::MigrateResultRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::MigrateResultReply>>(PrepareAsyncNotifyVRMigrateResultRaw(context, request, cq));
    }
    // 6: 迁移请求
    virtual ::grpc::Status DomainMigrate(::grpc::ClientContext* context, const ::virtrust::protos::DomainMigraterRequest& request, ::virtrust::protos::DomainMigraterReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::DomainMigraterReply>> AsyncDomainMigrate(::grpc::ClientContext* context, const ::virtrust::protos::DomainMigraterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::DomainMigraterReply>>(AsyncDomainMigrateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::DomainMigraterReply>> PrepareAsyncDomainMigrate(::grpc::ClientContext* context, const ::virtrust::protos::DomainMigraterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::DomainMigraterReply>>(PrepareAsyncDomainMigrateRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 1: 准备迁移
      virtual void PrepareMigration(::grpc::ClientContext* context, const ::virtrust::protos::PrepareMigRequest* request, ::virtrust::protos::PrepareMigReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PrepareMigration(::grpc::ClientContext* context, const ::virtrust::protos::PrepareMigRequest* request, ::virtrust::protos::PrepareMigReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 2: 交换公钥
      virtual void ExchangePkAndReport(::grpc::ClientContext* context, const ::virtrust::protos::EXchangePkAndReportRequest* request, ::virtrust::protos::EXchangePkAndReportReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ExchangePkAndReport(::grpc::ClientContext* context, const ::virtrust::protos::EXchangePkAndReportRequest* request, ::virtrust::protos::EXchangePkAndReportReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 3: 开始迁移
      virtual void StartMigration(::grpc::ClientContext* context, const ::virtrust::protos::StartMigRequest* request, ::virtrust::protos::StartMigReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StartMigration(::grpc::ClientContext* context, const ::virtrust::protos::StartMigRequest* request, ::virtrust::protos::StartMigReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 4：迁移虚机密码资源
      virtual void SendVRsourceData(::grpc::ClientContext* context, const ::virtrust::protos::VRsourceInfoRequest* request, ::virtrust::protos::VRsourceInfoReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendVRsourceData(::grpc::ClientContext* context, const ::virtrust::protos::VRsourceInfoRequest* request, ::virtrust::protos::VRsourceInfoReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 5: 通知迁移结果
      virtual void NotifyVRMigrateResult(::grpc::ClientContext* context, const ::virtrust::protos::MigrateResultRequest* request, ::virtrust::protos::MigrateResultReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void NotifyVRMigrateResult(::grpc::ClientContext* context, const ::virtrust::protos::MigrateResultRequest* request, ::virtrust::protos::MigrateResultReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 6: 迁移请求
      virtual void DomainMigrate(::grpc::ClientContext* context, const ::virtrust::protos::DomainMigraterRequest* request, ::virtrust::protos::DomainMigraterReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DomainMigrate(::grpc::ClientContext* context, const ::virtrust::protos::DomainMigraterRequest* request, ::virtrust::protos::DomainMigraterReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::PrepareMigReply>* AsyncPrepareMigrationRaw(::grpc::ClientContext* context, const ::virtrust::protos::PrepareMigRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::PrepareMigReply>* PrepareAsyncPrepareMigrationRaw(::grpc::ClientContext* context, const ::virtrust::protos::PrepareMigRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::EXchangePkAndReportReply>* AsyncExchangePkAndReportRaw(::grpc::ClientContext* context, const ::virtrust::protos::EXchangePkAndReportRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::EXchangePkAndReportReply>* PrepareAsyncExchangePkAndReportRaw(::grpc::ClientContext* context, const ::virtrust::protos::EXchangePkAndReportRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::StartMigReply>* AsyncStartMigrationRaw(::grpc::ClientContext* context, const ::virtrust::protos::StartMigRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::StartMigReply>* PrepareAsyncStartMigrationRaw(::grpc::ClientContext* context, const ::virtrust::protos::StartMigRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::VRsourceInfoReply>* AsyncSendVRsourceDataRaw(::grpc::ClientContext* context, const ::virtrust::protos::VRsourceInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::VRsourceInfoReply>* PrepareAsyncSendVRsourceDataRaw(::grpc::ClientContext* context, const ::virtrust::protos::VRsourceInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::MigrateResultReply>* AsyncNotifyVRMigrateResultRaw(::grpc::ClientContext* context, const ::virtrust::protos::MigrateResultRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::MigrateResultReply>* PrepareAsyncNotifyVRMigrateResultRaw(::grpc::ClientContext* context, const ::virtrust::protos::MigrateResultRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::DomainMigraterReply>* AsyncDomainMigrateRaw(::grpc::ClientContext* context, const ::virtrust::protos::DomainMigraterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::virtrust::protos::DomainMigraterReply>* PrepareAsyncDomainMigrateRaw(::grpc::ClientContext* context, const ::virtrust::protos::DomainMigraterRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status PrepareMigration(::grpc::ClientContext* context, const ::virtrust::protos::PrepareMigRequest& request, ::virtrust::protos::PrepareMigReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::PrepareMigReply>> AsyncPrepareMigration(::grpc::ClientContext* context, const ::virtrust::protos::PrepareMigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::PrepareMigReply>>(AsyncPrepareMigrationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::PrepareMigReply>> PrepareAsyncPrepareMigration(::grpc::ClientContext* context, const ::virtrust::protos::PrepareMigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::PrepareMigReply>>(PrepareAsyncPrepareMigrationRaw(context, request, cq));
    }
    ::grpc::Status ExchangePkAndReport(::grpc::ClientContext* context, const ::virtrust::protos::EXchangePkAndReportRequest& request, ::virtrust::protos::EXchangePkAndReportReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::EXchangePkAndReportReply>> AsyncExchangePkAndReport(::grpc::ClientContext* context, const ::virtrust::protos::EXchangePkAndReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::EXchangePkAndReportReply>>(AsyncExchangePkAndReportRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::EXchangePkAndReportReply>> PrepareAsyncExchangePkAndReport(::grpc::ClientContext* context, const ::virtrust::protos::EXchangePkAndReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::EXchangePkAndReportReply>>(PrepareAsyncExchangePkAndReportRaw(context, request, cq));
    }
    ::grpc::Status StartMigration(::grpc::ClientContext* context, const ::virtrust::protos::StartMigRequest& request, ::virtrust::protos::StartMigReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::StartMigReply>> AsyncStartMigration(::grpc::ClientContext* context, const ::virtrust::protos::StartMigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::StartMigReply>>(AsyncStartMigrationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::StartMigReply>> PrepareAsyncStartMigration(::grpc::ClientContext* context, const ::virtrust::protos::StartMigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::StartMigReply>>(PrepareAsyncStartMigrationRaw(context, request, cq));
    }
    ::grpc::Status SendVRsourceData(::grpc::ClientContext* context, const ::virtrust::protos::VRsourceInfoRequest& request, ::virtrust::protos::VRsourceInfoReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::VRsourceInfoReply>> AsyncSendVRsourceData(::grpc::ClientContext* context, const ::virtrust::protos::VRsourceInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::VRsourceInfoReply>>(AsyncSendVRsourceDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::VRsourceInfoReply>> PrepareAsyncSendVRsourceData(::grpc::ClientContext* context, const ::virtrust::protos::VRsourceInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::VRsourceInfoReply>>(PrepareAsyncSendVRsourceDataRaw(context, request, cq));
    }
    ::grpc::Status NotifyVRMigrateResult(::grpc::ClientContext* context, const ::virtrust::protos::MigrateResultRequest& request, ::virtrust::protos::MigrateResultReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::MigrateResultReply>> AsyncNotifyVRMigrateResult(::grpc::ClientContext* context, const ::virtrust::protos::MigrateResultRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::MigrateResultReply>>(AsyncNotifyVRMigrateResultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::MigrateResultReply>> PrepareAsyncNotifyVRMigrateResult(::grpc::ClientContext* context, const ::virtrust::protos::MigrateResultRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::MigrateResultReply>>(PrepareAsyncNotifyVRMigrateResultRaw(context, request, cq));
    }
    ::grpc::Status DomainMigrate(::grpc::ClientContext* context, const ::virtrust::protos::DomainMigraterRequest& request, ::virtrust::protos::DomainMigraterReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::DomainMigraterReply>> AsyncDomainMigrate(::grpc::ClientContext* context, const ::virtrust::protos::DomainMigraterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::DomainMigraterReply>>(AsyncDomainMigrateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::DomainMigraterReply>> PrepareAsyncDomainMigrate(::grpc::ClientContext* context, const ::virtrust::protos::DomainMigraterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::virtrust::protos::DomainMigraterReply>>(PrepareAsyncDomainMigrateRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void PrepareMigration(::grpc::ClientContext* context, const ::virtrust::protos::PrepareMigRequest* request, ::virtrust::protos::PrepareMigReply* response, std::function<void(::grpc::Status)>) override;
      void PrepareMigration(::grpc::ClientContext* context, const ::virtrust::protos::PrepareMigRequest* request, ::virtrust::protos::PrepareMigReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ExchangePkAndReport(::grpc::ClientContext* context, const ::virtrust::protos::EXchangePkAndReportRequest* request, ::virtrust::protos::EXchangePkAndReportReply* response, std::function<void(::grpc::Status)>) override;
      void ExchangePkAndReport(::grpc::ClientContext* context, const ::virtrust::protos::EXchangePkAndReportRequest* request, ::virtrust::protos::EXchangePkAndReportReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StartMigration(::grpc::ClientContext* context, const ::virtrust::protos::StartMigRequest* request, ::virtrust::protos::StartMigReply* response, std::function<void(::grpc::Status)>) override;
      void StartMigration(::grpc::ClientContext* context, const ::virtrust::protos::StartMigRequest* request, ::virtrust::protos::StartMigReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SendVRsourceData(::grpc::ClientContext* context, const ::virtrust::protos::VRsourceInfoRequest* request, ::virtrust::protos::VRsourceInfoReply* response, std::function<void(::grpc::Status)>) override;
      void SendVRsourceData(::grpc::ClientContext* context, const ::virtrust::protos::VRsourceInfoRequest* request, ::virtrust::protos::VRsourceInfoReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void NotifyVRMigrateResult(::grpc::ClientContext* context, const ::virtrust::protos::MigrateResultRequest* request, ::virtrust::protos::MigrateResultReply* response, std::function<void(::grpc::Status)>) override;
      void NotifyVRMigrateResult(::grpc::ClientContext* context, const ::virtrust::protos::MigrateResultRequest* request, ::virtrust::protos::MigrateResultReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DomainMigrate(::grpc::ClientContext* context, const ::virtrust::protos::DomainMigraterRequest* request, ::virtrust::protos::DomainMigraterReply* response, std::function<void(::grpc::Status)>) override;
      void DomainMigrate(::grpc::ClientContext* context, const ::virtrust::protos::DomainMigraterRequest* request, ::virtrust::protos::DomainMigraterReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::virtrust::protos::PrepareMigReply>* AsyncPrepareMigrationRaw(::grpc::ClientContext* context, const ::virtrust::protos::PrepareMigRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::virtrust::protos::PrepareMigReply>* PrepareAsyncPrepareMigrationRaw(::grpc::ClientContext* context, const ::virtrust::protos::PrepareMigRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::virtrust::protos::EXchangePkAndReportReply>* AsyncExchangePkAndReportRaw(::grpc::ClientContext* context, const ::virtrust::protos::EXchangePkAndReportRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::virtrust::protos::EXchangePkAndReportReply>* PrepareAsyncExchangePkAndReportRaw(::grpc::ClientContext* context, const ::virtrust::protos::EXchangePkAndReportRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::virtrust::protos::StartMigReply>* AsyncStartMigrationRaw(::grpc::ClientContext* context, const ::virtrust::protos::StartMigRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::virtrust::protos::StartMigReply>* PrepareAsyncStartMigrationRaw(::grpc::ClientContext* context, const ::virtrust::protos::StartMigRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::virtrust::protos::VRsourceInfoReply>* AsyncSendVRsourceDataRaw(::grpc::ClientContext* context, const ::virtrust::protos::VRsourceInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::virtrust::protos::VRsourceInfoReply>* PrepareAsyncSendVRsourceDataRaw(::grpc::ClientContext* context, const ::virtrust::protos::VRsourceInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::virtrust::protos::MigrateResultReply>* AsyncNotifyVRMigrateResultRaw(::grpc::ClientContext* context, const ::virtrust::protos::MigrateResultRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::virtrust::protos::MigrateResultReply>* PrepareAsyncNotifyVRMigrateResultRaw(::grpc::ClientContext* context, const ::virtrust::protos::MigrateResultRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::virtrust::protos::DomainMigraterReply>* AsyncDomainMigrateRaw(::grpc::ClientContext* context, const ::virtrust::protos::DomainMigraterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::virtrust::protos::DomainMigraterReply>* PrepareAsyncDomainMigrateRaw(::grpc::ClientContext* context, const ::virtrust::protos::DomainMigraterRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PrepareMigration_;
    const ::grpc::internal::RpcMethod rpcmethod_ExchangePkAndReport_;
    const ::grpc::internal::RpcMethod rpcmethod_StartMigration_;
    const ::grpc::internal::RpcMethod rpcmethod_SendVRsourceData_;
    const ::grpc::internal::RpcMethod rpcmethod_NotifyVRMigrateResult_;
    const ::grpc::internal::RpcMethod rpcmethod_DomainMigrate_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 1: 准备迁移
    virtual ::grpc::Status PrepareMigration(::grpc::ServerContext* context, const ::virtrust::protos::PrepareMigRequest* request, ::virtrust::protos::PrepareMigReply* response);
    // 2: 交换公钥
    virtual ::grpc::Status ExchangePkAndReport(::grpc::ServerContext* context, const ::virtrust::protos::EXchangePkAndReportRequest* request, ::virtrust::protos::EXchangePkAndReportReply* response);
    // 3: 开始迁移
    virtual ::grpc::Status StartMigration(::grpc::ServerContext* context, const ::virtrust::protos::StartMigRequest* request, ::virtrust::protos::StartMigReply* response);
    // 4：迁移虚机密码资源
    virtual ::grpc::Status SendVRsourceData(::grpc::ServerContext* context, const ::virtrust::protos::VRsourceInfoRequest* request, ::virtrust::protos::VRsourceInfoReply* response);
    // 5: 通知迁移结果
    virtual ::grpc::Status NotifyVRMigrateResult(::grpc::ServerContext* context, const ::virtrust::protos::MigrateResultRequest* request, ::virtrust::protos::MigrateResultReply* response);
    // 6: 迁移请求
    virtual ::grpc::Status DomainMigrate(::grpc::ServerContext* context, const ::virtrust::protos::DomainMigraterRequest* request, ::virtrust::protos::DomainMigraterReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_PrepareMigration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PrepareMigration() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PrepareMigration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrepareMigration(::grpc::ServerContext* /*context*/, const ::virtrust::protos::PrepareMigRequest* /*request*/, ::virtrust::protos::PrepareMigReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPrepareMigration(::grpc::ServerContext* context, ::virtrust::protos::PrepareMigRequest* request, ::grpc::ServerAsyncResponseWriter< ::virtrust::protos::PrepareMigReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ExchangePkAndReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ExchangePkAndReport() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ExchangePkAndReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExchangePkAndReport(::grpc::ServerContext* /*context*/, const ::virtrust::protos::EXchangePkAndReportRequest* /*request*/, ::virtrust::protos::EXchangePkAndReportReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExchangePkAndReport(::grpc::ServerContext* context, ::virtrust::protos::EXchangePkAndReportRequest* request, ::grpc::ServerAsyncResponseWriter< ::virtrust::protos::EXchangePkAndReportReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StartMigration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StartMigration() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_StartMigration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartMigration(::grpc::ServerContext* /*context*/, const ::virtrust::protos::StartMigRequest* /*request*/, ::virtrust::protos::StartMigReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartMigration(::grpc::ServerContext* context, ::virtrust::protos::StartMigRequest* request, ::grpc::ServerAsyncResponseWriter< ::virtrust::protos::StartMigReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SendVRsourceData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendVRsourceData() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_SendVRsourceData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendVRsourceData(::grpc::ServerContext* /*context*/, const ::virtrust::protos::VRsourceInfoRequest* /*request*/, ::virtrust::protos::VRsourceInfoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendVRsourceData(::grpc::ServerContext* context, ::virtrust::protos::VRsourceInfoRequest* request, ::grpc::ServerAsyncResponseWriter< ::virtrust::protos::VRsourceInfoReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_NotifyVRMigrateResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_NotifyVRMigrateResult() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_NotifyVRMigrateResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyVRMigrateResult(::grpc::ServerContext* /*context*/, const ::virtrust::protos::MigrateResultRequest* /*request*/, ::virtrust::protos::MigrateResultReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNotifyVRMigrateResult(::grpc::ServerContext* context, ::virtrust::protos::MigrateResultRequest* request, ::grpc::ServerAsyncResponseWriter< ::virtrust::protos::MigrateResultReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DomainMigrate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DomainMigrate() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_DomainMigrate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DomainMigrate(::grpc::ServerContext* /*context*/, const ::virtrust::protos::DomainMigraterRequest* /*request*/, ::virtrust::protos::DomainMigraterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDomainMigrate(::grpc::ServerContext* context, ::virtrust::protos::DomainMigraterRequest* request, ::grpc::ServerAsyncResponseWriter< ::virtrust::protos::DomainMigraterReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PrepareMigration<WithAsyncMethod_ExchangePkAndReport<WithAsyncMethod_StartMigration<WithAsyncMethod_SendVRsourceData<WithAsyncMethod_NotifyVRMigrateResult<WithAsyncMethod_DomainMigrate<Service > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_PrepareMigration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PrepareMigration() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::virtrust::protos::PrepareMigRequest, ::virtrust::protos::PrepareMigReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::virtrust::protos::PrepareMigRequest* request, ::virtrust::protos::PrepareMigReply* response) { return this->PrepareMigration(context, request, response); }));}
    void SetMessageAllocatorFor_PrepareMigration(
        ::grpc::MessageAllocator< ::virtrust::protos::PrepareMigRequest, ::virtrust::protos::PrepareMigReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::virtrust::protos::PrepareMigRequest, ::virtrust::protos::PrepareMigReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PrepareMigration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrepareMigration(::grpc::ServerContext* /*context*/, const ::virtrust::protos::PrepareMigRequest* /*request*/, ::virtrust::protos::PrepareMigReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PrepareMigration(
      ::grpc::CallbackServerContext* /*context*/, const ::virtrust::protos::PrepareMigRequest* /*request*/, ::virtrust::protos::PrepareMigReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ExchangePkAndReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ExchangePkAndReport() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::virtrust::protos::EXchangePkAndReportRequest, ::virtrust::protos::EXchangePkAndReportReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::virtrust::protos::EXchangePkAndReportRequest* request, ::virtrust::protos::EXchangePkAndReportReply* response) { return this->ExchangePkAndReport(context, request, response); }));}
    void SetMessageAllocatorFor_ExchangePkAndReport(
        ::grpc::MessageAllocator< ::virtrust::protos::EXchangePkAndReportRequest, ::virtrust::protos::EXchangePkAndReportReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::virtrust::protos::EXchangePkAndReportRequest, ::virtrust::protos::EXchangePkAndReportReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ExchangePkAndReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExchangePkAndReport(::grpc::ServerContext* /*context*/, const ::virtrust::protos::EXchangePkAndReportRequest* /*request*/, ::virtrust::protos::EXchangePkAndReportReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExchangePkAndReport(
      ::grpc::CallbackServerContext* /*context*/, const ::virtrust::protos::EXchangePkAndReportRequest* /*request*/, ::virtrust::protos::EXchangePkAndReportReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StartMigration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StartMigration() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::virtrust::protos::StartMigRequest, ::virtrust::protos::StartMigReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::virtrust::protos::StartMigRequest* request, ::virtrust::protos::StartMigReply* response) { return this->StartMigration(context, request, response); }));}
    void SetMessageAllocatorFor_StartMigration(
        ::grpc::MessageAllocator< ::virtrust::protos::StartMigRequest, ::virtrust::protos::StartMigReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::virtrust::protos::StartMigRequest, ::virtrust::protos::StartMigReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_StartMigration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartMigration(::grpc::ServerContext* /*context*/, const ::virtrust::protos::StartMigRequest* /*request*/, ::virtrust::protos::StartMigReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StartMigration(
      ::grpc::CallbackServerContext* /*context*/, const ::virtrust::protos::StartMigRequest* /*request*/, ::virtrust::protos::StartMigReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SendVRsourceData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendVRsourceData() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::virtrust::protos::VRsourceInfoRequest, ::virtrust::protos::VRsourceInfoReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::virtrust::protos::VRsourceInfoRequest* request, ::virtrust::protos::VRsourceInfoReply* response) { return this->SendVRsourceData(context, request, response); }));}
    void SetMessageAllocatorFor_SendVRsourceData(
        ::grpc::MessageAllocator< ::virtrust::protos::VRsourceInfoRequest, ::virtrust::protos::VRsourceInfoReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::virtrust::protos::VRsourceInfoRequest, ::virtrust::protos::VRsourceInfoReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendVRsourceData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendVRsourceData(::grpc::ServerContext* /*context*/, const ::virtrust::protos::VRsourceInfoRequest* /*request*/, ::virtrust::protos::VRsourceInfoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendVRsourceData(
      ::grpc::CallbackServerContext* /*context*/, const ::virtrust::protos::VRsourceInfoRequest* /*request*/, ::virtrust::protos::VRsourceInfoReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_NotifyVRMigrateResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_NotifyVRMigrateResult() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::virtrust::protos::MigrateResultRequest, ::virtrust::protos::MigrateResultReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::virtrust::protos::MigrateResultRequest* request, ::virtrust::protos::MigrateResultReply* response) { return this->NotifyVRMigrateResult(context, request, response); }));}
    void SetMessageAllocatorFor_NotifyVRMigrateResult(
        ::grpc::MessageAllocator< ::virtrust::protos::MigrateResultRequest, ::virtrust::protos::MigrateResultReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::virtrust::protos::MigrateResultRequest, ::virtrust::protos::MigrateResultReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_NotifyVRMigrateResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyVRMigrateResult(::grpc::ServerContext* /*context*/, const ::virtrust::protos::MigrateResultRequest* /*request*/, ::virtrust::protos::MigrateResultReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* NotifyVRMigrateResult(
      ::grpc::CallbackServerContext* /*context*/, const ::virtrust::protos::MigrateResultRequest* /*request*/, ::virtrust::protos::MigrateResultReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DomainMigrate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DomainMigrate() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::virtrust::protos::DomainMigraterRequest, ::virtrust::protos::DomainMigraterReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::virtrust::protos::DomainMigraterRequest* request, ::virtrust::protos::DomainMigraterReply* response) { return this->DomainMigrate(context, request, response); }));}
    void SetMessageAllocatorFor_DomainMigrate(
        ::grpc::MessageAllocator< ::virtrust::protos::DomainMigraterRequest, ::virtrust::protos::DomainMigraterReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::virtrust::protos::DomainMigraterRequest, ::virtrust::protos::DomainMigraterReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DomainMigrate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DomainMigrate(::grpc::ServerContext* /*context*/, const ::virtrust::protos::DomainMigraterRequest* /*request*/, ::virtrust::protos::DomainMigraterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DomainMigrate(
      ::grpc::CallbackServerContext* /*context*/, const ::virtrust::protos::DomainMigraterRequest* /*request*/, ::virtrust::protos::DomainMigraterReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_PrepareMigration<WithCallbackMethod_ExchangePkAndReport<WithCallbackMethod_StartMigration<WithCallbackMethod_SendVRsourceData<WithCallbackMethod_NotifyVRMigrateResult<WithCallbackMethod_DomainMigrate<Service > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_PrepareMigration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PrepareMigration() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PrepareMigration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrepareMigration(::grpc::ServerContext* /*context*/, const ::virtrust::protos::PrepareMigRequest* /*request*/, ::virtrust::protos::PrepareMigReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ExchangePkAndReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ExchangePkAndReport() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ExchangePkAndReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExchangePkAndReport(::grpc::ServerContext* /*context*/, const ::virtrust::protos::EXchangePkAndReportRequest* /*request*/, ::virtrust::protos::EXchangePkAndReportReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StartMigration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StartMigration() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_StartMigration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartMigration(::grpc::ServerContext* /*context*/, const ::virtrust::protos::StartMigRequest* /*request*/, ::virtrust::protos::StartMigReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SendVRsourceData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendVRsourceData() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_SendVRsourceData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendVRsourceData(::grpc::ServerContext* /*context*/, const ::virtrust::protos::VRsourceInfoRequest* /*request*/, ::virtrust::protos::VRsourceInfoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_NotifyVRMigrateResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_NotifyVRMigrateResult() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_NotifyVRMigrateResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyVRMigrateResult(::grpc::ServerContext* /*context*/, const ::virtrust::protos::MigrateResultRequest* /*request*/, ::virtrust::protos::MigrateResultReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DomainMigrate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DomainMigrate() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_DomainMigrate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DomainMigrate(::grpc::ServerContext* /*context*/, const ::virtrust::protos::DomainMigraterRequest* /*request*/, ::virtrust::protos::DomainMigraterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_PrepareMigration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PrepareMigration() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_PrepareMigration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrepareMigration(::grpc::ServerContext* /*context*/, const ::virtrust::protos::PrepareMigRequest* /*request*/, ::virtrust::protos::PrepareMigReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPrepareMigration(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ExchangePkAndReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ExchangePkAndReport() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ExchangePkAndReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExchangePkAndReport(::grpc::ServerContext* /*context*/, const ::virtrust::protos::EXchangePkAndReportRequest* /*request*/, ::virtrust::protos::EXchangePkAndReportReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExchangePkAndReport(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StartMigration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StartMigration() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_StartMigration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartMigration(::grpc::ServerContext* /*context*/, const ::virtrust::protos::StartMigRequest* /*request*/, ::virtrust::protos::StartMigReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartMigration(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendVRsourceData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendVRsourceData() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_SendVRsourceData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendVRsourceData(::grpc::ServerContext* /*context*/, const ::virtrust::protos::VRsourceInfoRequest* /*request*/, ::virtrust::protos::VRsourceInfoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendVRsourceData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_NotifyVRMigrateResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_NotifyVRMigrateResult() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_NotifyVRMigrateResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyVRMigrateResult(::grpc::ServerContext* /*context*/, const ::virtrust::protos::MigrateResultRequest* /*request*/, ::virtrust::protos::MigrateResultReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNotifyVRMigrateResult(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DomainMigrate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DomainMigrate() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_DomainMigrate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DomainMigrate(::grpc::ServerContext* /*context*/, const ::virtrust::protos::DomainMigraterRequest* /*request*/, ::virtrust::protos::DomainMigraterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDomainMigrate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PrepareMigration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PrepareMigration() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PrepareMigration(context, request, response); }));
    }
    ~WithRawCallbackMethod_PrepareMigration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrepareMigration(::grpc::ServerContext* /*context*/, const ::virtrust::protos::PrepareMigRequest* /*request*/, ::virtrust::protos::PrepareMigReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PrepareMigration(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ExchangePkAndReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ExchangePkAndReport() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ExchangePkAndReport(context, request, response); }));
    }
    ~WithRawCallbackMethod_ExchangePkAndReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExchangePkAndReport(::grpc::ServerContext* /*context*/, const ::virtrust::protos::EXchangePkAndReportRequest* /*request*/, ::virtrust::protos::EXchangePkAndReportReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExchangePkAndReport(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StartMigration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StartMigration() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StartMigration(context, request, response); }));
    }
    ~WithRawCallbackMethod_StartMigration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartMigration(::grpc::ServerContext* /*context*/, const ::virtrust::protos::StartMigRequest* /*request*/, ::virtrust::protos::StartMigReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StartMigration(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendVRsourceData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendVRsourceData() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendVRsourceData(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendVRsourceData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendVRsourceData(::grpc::ServerContext* /*context*/, const ::virtrust::protos::VRsourceInfoRequest* /*request*/, ::virtrust::protos::VRsourceInfoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendVRsourceData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_NotifyVRMigrateResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_NotifyVRMigrateResult() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->NotifyVRMigrateResult(context, request, response); }));
    }
    ~WithRawCallbackMethod_NotifyVRMigrateResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyVRMigrateResult(::grpc::ServerContext* /*context*/, const ::virtrust::protos::MigrateResultRequest* /*request*/, ::virtrust::protos::MigrateResultReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* NotifyVRMigrateResult(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DomainMigrate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DomainMigrate() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DomainMigrate(context, request, response); }));
    }
    ~WithRawCallbackMethod_DomainMigrate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DomainMigrate(::grpc::ServerContext* /*context*/, const ::virtrust::protos::DomainMigraterRequest* /*request*/, ::virtrust::protos::DomainMigraterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DomainMigrate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PrepareMigration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PrepareMigration() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::virtrust::protos::PrepareMigRequest, ::virtrust::protos::PrepareMigReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::virtrust::protos::PrepareMigRequest, ::virtrust::protos::PrepareMigReply>* streamer) {
                       return this->StreamedPrepareMigration(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PrepareMigration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PrepareMigration(::grpc::ServerContext* /*context*/, const ::virtrust::protos::PrepareMigRequest* /*request*/, ::virtrust::protos::PrepareMigReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPrepareMigration(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::virtrust::protos::PrepareMigRequest,::virtrust::protos::PrepareMigReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ExchangePkAndReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ExchangePkAndReport() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::virtrust::protos::EXchangePkAndReportRequest, ::virtrust::protos::EXchangePkAndReportReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::virtrust::protos::EXchangePkAndReportRequest, ::virtrust::protos::EXchangePkAndReportReply>* streamer) {
                       return this->StreamedExchangePkAndReport(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ExchangePkAndReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ExchangePkAndReport(::grpc::ServerContext* /*context*/, const ::virtrust::protos::EXchangePkAndReportRequest* /*request*/, ::virtrust::protos::EXchangePkAndReportReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedExchangePkAndReport(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::virtrust::protos::EXchangePkAndReportRequest,::virtrust::protos::EXchangePkAndReportReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StartMigration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StartMigration() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::virtrust::protos::StartMigRequest, ::virtrust::protos::StartMigReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::virtrust::protos::StartMigRequest, ::virtrust::protos::StartMigReply>* streamer) {
                       return this->StreamedStartMigration(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StartMigration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StartMigration(::grpc::ServerContext* /*context*/, const ::virtrust::protos::StartMigRequest* /*request*/, ::virtrust::protos::StartMigReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStartMigration(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::virtrust::protos::StartMigRequest,::virtrust::protos::StartMigReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendVRsourceData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendVRsourceData() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::virtrust::protos::VRsourceInfoRequest, ::virtrust::protos::VRsourceInfoReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::virtrust::protos::VRsourceInfoRequest, ::virtrust::protos::VRsourceInfoReply>* streamer) {
                       return this->StreamedSendVRsourceData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendVRsourceData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendVRsourceData(::grpc::ServerContext* /*context*/, const ::virtrust::protos::VRsourceInfoRequest* /*request*/, ::virtrust::protos::VRsourceInfoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendVRsourceData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::virtrust::protos::VRsourceInfoRequest,::virtrust::protos::VRsourceInfoReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_NotifyVRMigrateResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_NotifyVRMigrateResult() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::virtrust::protos::MigrateResultRequest, ::virtrust::protos::MigrateResultReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::virtrust::protos::MigrateResultRequest, ::virtrust::protos::MigrateResultReply>* streamer) {
                       return this->StreamedNotifyVRMigrateResult(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_NotifyVRMigrateResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status NotifyVRMigrateResult(::grpc::ServerContext* /*context*/, const ::virtrust::protos::MigrateResultRequest* /*request*/, ::virtrust::protos::MigrateResultReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedNotifyVRMigrateResult(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::virtrust::protos::MigrateResultRequest,::virtrust::protos::MigrateResultReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DomainMigrate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DomainMigrate() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::virtrust::protos::DomainMigraterRequest, ::virtrust::protos::DomainMigraterReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::virtrust::protos::DomainMigraterRequest, ::virtrust::protos::DomainMigraterReply>* streamer) {
                       return this->StreamedDomainMigrate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DomainMigrate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DomainMigrate(::grpc::ServerContext* /*context*/, const ::virtrust::protos::DomainMigraterRequest* /*request*/, ::virtrust::protos::DomainMigraterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDomainMigrate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::virtrust::protos::DomainMigraterRequest,::virtrust::protos::DomainMigraterReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_PrepareMigration<WithStreamedUnaryMethod_ExchangePkAndReport<WithStreamedUnaryMethod_StartMigration<WithStreamedUnaryMethod_SendVRsourceData<WithStreamedUnaryMethod_NotifyVRMigrateResult<WithStreamedUnaryMethod_DomainMigrate<Service > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_PrepareMigration<WithStreamedUnaryMethod_ExchangePkAndReport<WithStreamedUnaryMethod_StartMigration<WithStreamedUnaryMethod_SendVRsourceData<WithStreamedUnaryMethod_NotifyVRMigrateResult<WithStreamedUnaryMethod_DomainMigrate<Service > > > > > > StreamedService;
};

}  // namespace protos
}  // namespace virtrust


#endif  // GRPC_migrate_2eproto__INCLUDED
